version: '3.6'
services:
  postgres:
    image: postgres:11-alpine
    restart: always
    ports:
    - "5432:5432"
    volumes:
    - db:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: dev
  redis:
    image: redis:5-alpine
    restart: always
    ports:
    - "6379:6379"
    volumes:
    - redis:/var/lib/redis/data
    command: ["redis-server", "--appendonly", "yes"]
volumes:
  db:
  redis:
