version: "3.6"
services:
  postgres:
    image: postgres:11-alpine
    restart: always
    ports:
    - "5432:5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
  redis:
    image: redis:5-alpine
    restart: always
    ports:
    - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
