version: '3.6'
services:
  postgres:
    image: postgres:11-alpine
    restart: always
    ports:
    - "5433:5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: postgres
  redis:
    image: redis:5-alpine
    restart: always
    ports:
    - "6380:6379"
    command: ["redis-server", "--appendonly", "yes"]
